export type Course = readonly [name: string, category: string, icon: string];

export const popularCourses: readonly Course[] = [
  ["Java", "Coding", "☕"],
  ["Python", "Coding", "🐍"],
  ["JavaScript", "Coding", "◇"],
  ["C++", "Coding", "⌘"],
  ["Web Development", "Coding", "▤"],
  ["Data Structures", "Coding", "⌘"],
  ["Algorithms", "Coding", "↯"],
  ["SQL & Databases", "Coding", "▦"],
  ["Machine Learning", "Technology", "◉"],
  ["Cybersecurity", "Technology", "◇"],
  ["Calculus", "Mathematics", "∫"],
  ["Algebra", "Mathematics", "∑"],
  ["Statistics", "Mathematics", "◌"],
  ["Geometry", "Mathematics", "△"],
  ["Discrete Mathematics", "Mathematics", "∞"],
  ["Physics", "Science", "⚛"],
  ["Chemistry", "Science", "⚗"],
  ["Biology", "Science", "♧"],
  ["Environmental Science", "Science", "♧"],
  ["Astronomy", "Science", "✦"],
  ["Economics", "Business", "◒"],
  ["Accounting", "Business", "▥"],
  ["Marketing", "Business", "↗"],
  ["Project Management", "Business", "✓"],
  ["Finance", "Business", "$"],
  ["Psychology", "Humanities", "◉"],
  ["Communication", "Humanities", "✎"],
  ["Research Methods", "Humanities", "⌕"],
  ["English Language", "Languages", "Aa"],
  ["Design Thinking", "Creative", "✧"],
];
